var s = "highlight",
  r = "resources_well_progress_click_up",
  e = "resources_well_progress_click_down",
  _ = "resources_well_progress_done_start",
  a = "resources_well_progress_done_stop",
  c = "resources_well_progress_click_oneshot",
  o = "bp_highlight",
  l = "bp_click",
  g = "gui_hangar_award_screen",
  u = "gui_hangar_award_tank_01",
  i = "ach_sub_glare",
  h = { click: { "resource-card": r }, "mouse-enter": { "resource-card": o } };
export {
  a,
  o as c,
  c as d,
  h as f,
  _ as i,
  s as l,
  g as n,
  l as o,
  u as r,
  e as s,
  i as t,
  r as u,
};
