const s = "highlight",
  e = "resources_well_progress_click_up",
  r = "resources_well_progress_click_down",
  _ = "resources_well_progress_done_start",
  a = "resources_well_progress_done_stop",
  c = "resources_well_progress_click_oneshot",
  o = "bp_highlight",
  l = "bp_click",
  g = "gui_hangar_award_screen",
  u = "gui_hangar_award_tank_01",
  h = "ach_sub_glare",
  i = { click: { "resource-card": e }, "mouse-enter": { "resource-card": o } };
export {
  h as G,
  g as O,
  u as S,
  s as a,
  e as b,
  r as c,
  o as d,
  l as e,
  _ as f,
  c as g,
  a as h,
  i as t,
};
