import { r as e, f as _, j as a } from "./vendor.js";
import "./lib.js";
const r = {
  box: "Box_68e49f7e",
  relative: "Box_relative_fd050574",
  row: "Box_row_1925f405",
  col: "Box_col_ad448e00",
  wrap: "Box_wrap_6cdd949a",
  nowrap: "Box_nowrap_a69f018",
  "items-start": "Box_items-start_16563606",
  "items-center": "Box_items-center_6d036fce",
  "items-end": "Box_items-end_269bb8b4",
  "items-stretch": "Box_items-stretch_cef7a22d",
  "justify-start": "Box_justify-start_fa88c356",
  "justify-center": "Box_justify-center_314da992",
  "justify-end": "Box_justify-end_9869743f",
  "justify-between": "Box_justify-between_3dcb092a",
  "justify-around": "Box_justify-around_4802e887",
  "self-start": "Box_self-start_ff5a8348",
  "self-center": "Box_self-center_ade4ba59",
  "self-end": "Box_self-end_3d8bf41d",
  "self-stretch": "Box_self-stretch_be769d6",
  flex: "Box_flex_bc047b4e",
  grow: "Box_grow_4ba4bb70",
  shrink: "Box_shrink_c4d3ac2e",
  "shrink-0": "Box_shrink-0_bb43e4c",
  "m-xs": "Box_m-xs_4534869f",
  "m-sm": "Box_m-sm_8a9cdeab",
  "m-md": "Box_m-md_e6f12366",
  "m-lg": "Box_m-lg_17da7724",
  "m-xl": "Box_m-xl_49c32875",
  "mt-xs": "Box_mt-xs_ae418bac",
  "mt-sm": "Box_mt-sm_f829d0f5",
  "mt-md": "Box_mt-md_48475e5f",
  "mt-lg": "Box_mt-lg_bdff7fb4",
  "mt-xl": "Box_mt-xl_5aec216",
  "mr-xs": "Box_mr-xs_4d2c9f47",
  "mr-sm": "Box_mr-sm_a86d0d5a",
  "mr-md": "Box_mr-md_3670df57",
  "mr-lg": "Box_mr-lg_c4ad8230",
  "mr-xl": "Box_mr-xl_903886b3",
  "mb-xs": "Box_mb-xs_9aef9eb6",
  "mb-sm": "Box_mb-sm_8cd126aa",
  "mb-md": "Box_mb-md_918d8859",
  "mb-lg": "Box_mb-lg_26f43e51",
  "mb-xl": "Box_mb-xl_fb54ad4d",
  "ml-xs": "Box_ml-xs_5ac127e0",
  "ml-sm": "Box_ml-sm_1f13c62b",
  "ml-md": "Box_ml-md_3071da33",
  "ml-lg": "Box_ml-lg_2e31850c",
  "ml-xl": "Box_ml-xl_14f4237b",
  "mx-xs": "Box_mx-xs_ca3592df",
  "mx-sm": "Box_mx-sm_cd340526",
  "mx-md": "Box_mx-md_7e187bf5",
  "mx-lg": "Box_mx-lg_f1480c8f",
  "mx-xl": "Box_mx-xl_2ddc5060",
  "my-xs": "Box_my-xs_740043b1",
  "my-sm": "Box_my-sm_abeb7c84",
  "my-md": "Box_my-md_85ff049d",
  "my-lg": "Box_my-lg_bc377fa1",
  "my-xl": "Box_my-xl_7b497209",
  "p-xs": "Box_p-xs_bbe5ef40",
  "p-sm": "Box_p-sm_e24e6f4c",
  "p-md": "Box_p-md_d25192ea",
  "p-lg": "Box_p-lg_af49147",
  "p-xl": "Box_p-xl_4e3c6003",
  "pt-xs": "Box_pt-xs_48caacee",
  "pt-sm": "Box_pt-sm_763bc2ea",
  "pt-md": "Box_pt-md_bb1551c9",
  "pt-lg": "Box_pt-lg_4452d882",
  "pt-xl": "Box_pt-xl_35a58a5f",
  "pr-xs": "Box_pr-xs_41bdc1b6",
  "pr-sm": "Box_pr-sm_b0f49302",
  "pr-md": "Box_pr-md_f754a2b0",
  "pr-lg": "Box_pr-lg_e19b1257",
  "pr-xl": "Box_pr-xl_9366962f",
  "pb-xs": "Box_pb-xs_c82bacb6",
  "pb-sm": "Box_pb-sm_b04f0ce5",
  "pb-md": "Box_pb-md_afa4ce1e",
  "pb-lg": "Box_pb-lg_3aaa43a5",
  "pb-xl": "Box_pb-xl_9bbfdff9",
  "pl-xs": "Box_pl-xs_77e20730",
  "pl-sm": "Box_pl-sm_cc4f7509",
  "pl-md": "Box_pl-md_579c9aa4",
  "pl-lg": "Box_pl-lg_9e53fdef",
  "pl-xl": "Box_pl-xl_1a10bf62",
  "px-xs": "Box_px-xs_98724f4b",
  "px-sm": "Box_px-sm_66523304",
  "px-md": "Box_px-md_b8773887",
  "px-lg": "Box_px-lg_2ce8012d",
  "px-xl": "Box_px-xl_df793893",
  "py-xs": "Box_py-xs_b1c76bae",
  "py-sm": "Box_py-sm_13a9aed8",
  "py-md": "Box_py-md_beed246e",
  "py-lg": "Box_py-lg_7281f52",
  "py-xl": "Box_py-xl_11afcd36",
};
function m(e) {
  return "number" == typeof e ? `${e}rem` : e;
}
const x = e.forwardRef(function (
    {
      relative: e,
      row: x,
      column: t,
      wrap: l,
      nowrap: d,
      items_start: o,
      items_center: s,
      items_end: p,
      items_stretch: n,
      justify_start: i,
      justify_center: g,
      justify_end: c,
      justify_between: h,
      justify_around: b,
      justify_evenly: f,
      self_start: y,
      self_center: B,
      self_end: u,
      self_stretch: T,
      flex: v,
      grow: j,
      shrink: w,
      shrink_0: k,
      m: L,
      mt: N,
      mr: R,
      mb: S,
      ml: $,
      mx: z,
      my: H,
      p: O,
      pt: P,
      pr: q,
      pb: A,
      pl: C,
      px: D,
      py: E,
      m_xs: F,
      m_sm: G,
      m_md: I,
      m_lg: J,
      m_xl: K,
      mt_xs: M,
      mt_sm: Q,
      mt_md: U,
      mt_lg: V,
      mt_xl: W,
      mr_xs: X,
      mr_sm: Y,
      mr_md: Z,
      mr_lg: ee,
      mr_xl: _e,
      mb_xs: ae,
      mb_sm: re,
      mb_md: me,
      mb_lg: xe,
      mb_xl: te,
      ml_xs: le,
      ml_sm: de,
      ml_md: oe,
      ml_lg: se,
      ml_xl: pe,
      mx_xs: ne,
      mx_sm: ie,
      mx_md: ge,
      mx_lg: ce,
      mx_xl: he,
      my_xs: be,
      my_sm: fe,
      my_md: ye,
      my_lg: Be,
      my_xl: ue,
      p_xs: Te,
      p_sm: ve,
      p_md: je,
      p_lg: we,
      p_xl: ke,
      pt_xs: Le,
      pt_sm: Ne,
      pt_md: Re,
      pt_lg: Se,
      pt_xl: $e,
      pr_xs: ze,
      pr_sm: He,
      pr_md: Oe,
      pr_lg: Pe,
      pr_xl: qe,
      pb_xs: Ae,
      pb_sm: Ce,
      pb_md: De,
      pb_lg: Ee,
      pb_xl: Fe,
      pl_xs: Ge,
      pl_sm: Ie,
      pl_md: Je,
      pl_lg: Ke,
      pl_xl: Me,
      px_xs: Qe,
      px_sm: Ue,
      px_md: Ve,
      px_lg: We,
      px_xl: Xe,
      py_xs: Ye,
      py_sm: Ze,
      py_md: e_,
      py_lg: __,
      py_xl: a_,
      component: r_,
      className: m_,
      style: x_,
      children: t_,
      ...l_
    },
    d_,
  ) {
    const o_ = r_ ?? "div",
      s_ = _(
        r.box,
        e ? r.relative : void 0,
        t ? r.col : r.row,
        l && r.wrap,
        d && r.nowrap,
        o && r["items-start"],
        s && r["items-center"],
        p && r["items-end"],
        n && r["items-stretch"],
        i && r["justify-start"],
        g && r["justify-center"],
        c && r["justify-end"],
        h && r["justify-between"],
        b && r["justify-around"],
        f && r["justify-evenly"],
        y && r["self-start"],
        B && r["self-center"],
        u && r["self-end"],
        T && r["self-stretch"],
        v && r.flex,
        j && r.grow,
        w && r.shrink,
        k && r["shrink-0"],
        F && r["m-xs"],
        G && r["m-sm"],
        I && r["m-md"],
        J && r["m-lg"],
        K && r["m-xl"],
        M && r["mt-xs"],
        Q && r["mt-sm"],
        U && r["mt-md"],
        V && r["mt-lg"],
        W && r["mt-xl"],
        X && r["mr-xs"],
        Y && r["mr-sm"],
        Z && r["mr-md"],
        ee && r["mr-lg"],
        _e && r["mr-xl"],
        ae && r["mb-xs"],
        re && r["mb-sm"],
        me && r["mb-md"],
        xe && r["mb-lg"],
        te && r["mb-xl"],
        le && r["ml-xs"],
        de && r["ml-sm"],
        oe && r["ml-md"],
        se && r["ml-lg"],
        pe && r["ml-xl"],
        ne && r["mx-xs"],
        ie && r["mx-sm"],
        ge && r["mx-md"],
        ce && r["mx-lg"],
        he && r["mx-xl"],
        be && r["my-xs"],
        fe && r["my-sm"],
        ye && r["my-md"],
        Be && r["my-lg"],
        ue && r["my-xl"],
        Te && r["p-xs"],
        ve && r["p-sm"],
        je && r["p-md"],
        we && r["p-lg"],
        ke && r["p-xl"],
        Le && r["pt-xs"],
        Ne && r["pt-sm"],
        Re && r["pt-md"],
        Se && r["pt-lg"],
        $e && r["pt-xl"],
        ze && r["pr-xs"],
        He && r["pr-sm"],
        Oe && r["pr-md"],
        Pe && r["pr-lg"],
        qe && r["pr-xl"],
        Ae && r["pb-xs"],
        Ce && r["pb-sm"],
        De && r["pb-md"],
        Ee && r["pb-lg"],
        Fe && r["pb-xl"],
        Ge && r["pl-xs"],
        Ie && r["pl-sm"],
        Je && r["pl-md"],
        Ke && r["pl-lg"],
        Me && r["pl-xl"],
        Qe && r["px-xs"],
        Ue && r["px-sm"],
        Ve && r["px-md"],
        We && r["px-lg"],
        Xe && r["px-xl"],
        Ye && r["py-xs"],
        Ze && r["py-sm"],
        e_ && r["py-md"],
        __ && r["py-lg"],
        a_ && r["py-xl"],
        m_,
      ),
      p_ = {
        ...(void 0 !== L && {
          marginTop: m(L),
          marginRight: m(L),
          marginBottom: m(L),
          marginLeft: m(L),
        }),
        ...(void 0 !== O && {
          paddingTop: m(O),
          paddingRight: m(O),
          paddingBottom: m(O),
          paddingLeft: m(O),
        }),
        ...(void 0 !== N && { marginTop: m(N) }),
        ...(void 0 !== R && { marginRight: m(R) }),
        ...(void 0 !== S && { marginBottom: m(S) }),
        ...(void 0 !== $ && { marginLeft: m($) }),
        ...(void 0 !== P && { paddingTop: m(P) }),
        ...(void 0 !== q && { paddingRight: m(q) }),
        ...(void 0 !== A && { paddingBottom: m(A) }),
        ...(void 0 !== C && { paddingLeft: m(C) }),
        ...(void 0 !== z && { marginLeft: m(z), marginRight: m(z) }),
        ...(void 0 !== H && { marginTop: m(H), marginBottom: m(H) }),
        ...(void 0 !== D && { paddingLeft: m(D), paddingRight: m(D) }),
        ...(void 0 !== E && { paddingTop: m(E), paddingBottom: m(E) }),
        ...x_,
      },
      n_ = Object.keys(p_).length > 0;
    return a.jsx(o_, { ref: d_, className: s_, style: n_ ? p_ : void 0, ...l_, children: t_ });
  }),
  t = {
    h1: "Text_h1_a267657f",
    h2: "Text_h2_f4322be7",
    h3: "Text_h3_31f5189e",
    h4: "Text_h4_73375c7a",
    h5: "Text_h5_5edaee07",
    body: "Text_body_73952542",
    label: "Text_label_b0e7054b",
    "heading-80": "Text_heading-80_59693aff",
    "heading-56": "Text_heading-56_89b1fb8c",
    "heading-40": "Text_heading-40_a267657f",
    "heading-36": "Text_heading-36_67726b18",
    "heading-32": "Text_heading-32_f4322be7",
    "heading-28": "Text_heading-28_7e57382b",
    "heading-26": "Text_heading-26_6a1a3d9",
    "heading-24": "Text_heading-24_31f5189e",
    "heading-22": "Text_heading-22_6ff2d3ad",
    "heading-20": "Text_heading-20_73375c7a",
    "heading-18": "Text_heading-18_152bebcd",
    "heading-16": "Text_heading-16_5edaee07",
    "heading-15": "Text_heading-15_1999f131",
    "paragraph-24": "Text_paragraph-24_bac72a26",
    "paragraph-22": "Text_paragraph-22_8364596",
    "paragraph-20": "Text_paragraph-20_ee173bae",
    "paragraph-18": "Text_paragraph-18_20b0faaf",
    "paragraph-16": "Text_paragraph-16_73952542",
    "paragraph-15": "Text_paragraph-15_e3ba5ed2",
    "paragraph-14": "Text_paragraph-14_e7d51cac",
    "align-left": "Text_align-left_123bdbf3",
    "align-center": "Text_align-center_ee884d2e",
    "align-right": "Text_align-right_9151b039",
    "color-general-primary": "Text_color-general-primary_a7277fe6",
    "color-general-secondary": "Text_color-general-secondary_2462341a",
    "color-general-tertiary": "Text_color-general-tertiary_3da763ad",
    "color-general-dark": "Text_color-general-dark_b6fd6b4e",
    "color-currency-credits": "Text_color-currency-credits_c7ae9abe",
    "color-currency-gold": "Text_color-currency-gold_ea1d3899",
    "color-currency-bond": "Text_color-currency-bond_833f598",
    "color-currency-combat-experience": "Text_color-currency-combat-experience_94b4931b",
    "color-currency-free-experience": "Text_color-currency-free-experience_5fef03bd",
    "color-status-alert": "Text_color-status-alert_9d323214",
    "color-status-error": "Text_color-status-error_d4d223f0",
    "color-status-link": "Text_color-status-link_bd0377c0",
    "color-status-done": "Text_color-status-done_582dcd69",
    "color-team-killer": "Text_color-team-killer_1185b002",
  },
  l = new Set([
    "general-primary",
    "general-secondary",
    "general-tertiary",
    "general-dark",
    "currency-credits",
    "currency-gold",
    "currency-bond",
    "currency-combat-experience",
    "currency-free-experience",
    "status-alert",
    "status-error",
    "status-link",
    "status-done",
    "team-killer",
  ]),
  d = new Set([
    "heading-80",
    "heading-56",
    "heading-40",
    "heading-36",
    "heading-32",
    "heading-28",
    "heading-26",
    "heading-24",
    "heading-22",
    "heading-20",
    "heading-18",
    "heading-16",
    "heading-15",
    "paragraph-24",
    "paragraph-22",
    "paragraph-20",
    "paragraph-18",
    "paragraph-16",
    "paragraph-15",
    "paragraph-14",
    "h1",
    "h2",
    "h3",
    "h4",
    "h5",
    "body",
    "label",
  ]),
  o = {
    h1: "h1",
    h2: "h2",
    h3: "h3",
    h4: "h4",
    h5: "h5",
    body: "p",
    label: "span",
    "heading-80": "h1",
    "heading-56": "h1",
    "heading-40": "h1",
    "heading-36": "h2",
    "heading-32": "h2",
    "heading-28": "h2",
    "heading-26": "h2",
    "heading-24": "h3",
    "heading-22": "h3",
    "heading-20": "h4",
    "heading-18": "h4",
    "heading-16": "h5",
    "heading-15": "h5",
    "paragraph-24": "p",
    "paragraph-22": "p",
    "paragraph-20": "p",
    "paragraph-18": "p",
    "paragraph-16": "p",
    "paragraph-15": "p",
    "paragraph-14": "p",
    inherit: "p",
  };
function s({
  variant: e = "body",
  color: r,
  size: m,
  left: s,
  right: p,
  center: n,
  align: i = s ? "left" : p ? "right" : n ? "center" : void 0,
  component: g,
  className: c,
  style: h,
  ...b
}) {
  const f = g ?? o[e] ?? "div",
    y = !!r && void 0 !== (B = r) && l.has(B);
  var B;
  const u = y ? t[`color-${r}`] : void 0,
    T = void 0 === r || y ? void 0 : r,
    v = d.has(e) ? t[e] : void 0,
    j = void 0 !== i ? t[`align-${i}`] : void 0,
    w = { ...(void 0 !== T && { color: T }), ...(void 0 !== m && { fontSize: m }), ...h };
  return a.jsx(x, {
    component: f,
    className: _(v, u, j, c),
    style: Object.keys(w).length > 0 ? w : void 0,
    ...b,
  });
}
function p(e) {
  return a.jsx(s, { variant: "h3", ...e });
}
function n(e) {
  return a.jsx(s, { variant: "body", ...e });
}
function i(e) {
  return a.jsx(s, { variant: "label", ...e });
}
((p.displayName = "H3"), (n.displayName = "P"), (i.displayName = "Label"));
export { x as B, p as H, i as L, n as P, s as T };
